name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: PyV
      id: pyv
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: PyV
        setup-command: pip install pytest
        command: pytest -v
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        PYV_RESULTS: "${{steps.pyv.outputs.result}}"
      with:
        runners: pyv
